import{KEY,ICONS,dayKey,fresh,validate,complete,cancelCompletion,claim,saveItem}from'./core.mjs?v=1.1.0';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,storageError=false,tab='tasks',editing=null,selectedIcon=ICONS[0],toastTimer,date=dayKey();
function read(){const raw=localStorage.getItem(KEY);if(raw===null)return fresh();return validate(JSON.parse(raw));}
function write(s){validate(s);localStorage.setItem(KEY,JSON.stringify(s));state=s;storageError=false;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400);}
async function mutate(action){const run=()=>{if(storageError)throw Error('记录暂时无法读取，请先在设置中恢复备份。');const s=read();const result=action(s);write(s);render();return result;};try{return navigator.locks?.request?await navigator.locks.request(KEY,run):run();}catch(e){toast(e.message||'保存失败，请检查设备存储空间。');throw e;}}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('#confetti').innerHTML=Array.from({length:18},(_,i)=>`<span class="piece" style="--x:${Math.cos(i*2.4)*(90+i*15)}px;--y:${Math.sin(i*2.4)*(80+i*12)+70}px;--r:${i*38}deg;color:${['#f6c642','#7baeff','#87ccb0'][i%3]}">${i%3?'✦':'★'}</span>`).join('');setTimeout(()=>$('#confetti').replaceChildren(),1050);}
async function checkin(id){const ok=await mutate(s=>complete(s,id));toast(ok?'太棒啦！收获 1 颗星星 ⭐':'今天已经完成啦，明天再来！');if(ok)celebrate();return{added:ok,total:state.completions.length};}
function render(){
 date=dayKey();const tasks=state.tasks.filter(t=>t.active),today=new Set(state.completions.filter(c=>c.day===date).map(c=>c.taskId)),done=tasks.filter(t=>today.has(t.id)).length,total=state.completions.length;
 $('#total').textContent=total;$('#todayCount').textContent=`${done} / ${tasks.length}`;$('#taskCount').textContent=`${tasks.length} 项`;$('#ring').style.setProperty('--progress',`${tasks.length?done/tasks.length*100:0}%`);$('#dateLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
 $('#todayMessage').textContent=storageError?'记录未能读取，请到设置恢复备份。':!tasks.length?'先添加一个小任务吧。':done===tasks.length?'今日任务全部完成，真棒！':'完成一个任务，点亮一颗星。';
 const rewards=state.rewards.filter(r=>r.active).sort((a,b)=>a.threshold-b.threshold),next=rewards.find(r=>!state.claims.some(c=>c.rewardId===r.id));
 $('#nextGoal').textContent=next?(total>=next.threshold?`有奖励可以领取啦！`:`再攒 ${next.threshold-total} 颗星，解锁下一个奖励`):'每一份努力，都算数。';
 $('#tasks').innerHTML=tasks.length?tasks.map((t,i)=>{const d=today.has(t.id);return `<article class="task-card ${d?'done':''}"><div class="task-top"><div class="task-icon" style="--tile:${['#e9f1ff','#fff0df','#e9f6ef','#f2edff'][i%4]}">${t.icon}</div><span class="task-value">${d?'✓ 已点亮':'★ +1'}</span></div><h3>${esc(t.name)}</h3><p>累计完成 ${state.completions.filter(c=>c.taskId===t.id).length} 天</p><button class="complete-btn" data-complete="${esc(t.id)}" ${d||storageError?'disabled':''} aria-label="${esc(t.name)}：${d?'今日已完成':'完成并获得一颗星'}">${d?'✓ 今日已完成':'我完成啦 ＋'}</button>${d?`<button class="undo-btn" data-undo="${esc(t.id)}" ${storageError?'disabled':''} aria-label="取消${esc(t.name)}今天的打卡">↶ 取消打卡</button>`:''}</article>`;}).join(''):'<div class="empty">从一个小任务开始，收获第一颗星星。<button class="soft-btn" data-open="tasks">＋ 添加每日任务</button></div>';
 $('#rewards').innerHTML=rewards.length?rewards.map(r=>{const c=state.claims.find(c=>c.rewardId===r.id),ready=total>=r.threshold;return `<article class="reward-card ${ready&&!c?'ready':''}"><div class="reward-top"><span class="reward-icon">${r.icon}</span><div><h3>${esc(r.name)}</h3><div class="reward-meta">累计 ${r.threshold} 颗星</div></div></div><div class="bar" role="progressbar" aria-label="${esc(r.name)}进度" aria-valuemin="0" aria-valuemax="${r.threshold}" aria-valuenow="${Math.min(total,r.threshold)}"><div style="width:${Math.min(100,total/r.threshold*100)}%"></div></div><div class="reward-bottom"><span>${c?new Date(c.at).toLocaleDateString('zh-CN')+' 已领取':ready?'努力有回响！':`还差 ${r.threshold-total} 颗星`}</span>${c?'<span class="received">✓ 已领取</span>':`<button class="claim-btn" data-claim="${esc(r.id)}" ${!ready||storageError?'disabled':''}>${ready?'领取奖励':'尚未解锁'}</button>`}</div></article>`;}).join(''):'<div class="empty">设一个小心愿，让星星有个目的地。<button class="soft-btn" data-open="rewards">＋ 添加阶段奖励</button></div>';
 if($('#settings').open)renderSettings();
}
function openSettings(t='tasks'){tab=t;renderSettings();if(!$('#settings').open)$('#settings').showModal();}
function renderSettings(){
 document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-pressed',String(b.dataset.tab===tab));});
 if(tab==='data'){$('#settingsBody').innerHTML=`<p class="help">免登录，记录只保存在当前浏览器中。清除网站数据、使用无痕浏览或更换设备，可能失去记录。建议定期导出备份。</p><div class="setting-row"><div class="setting-name">已积攒 ${state.completions.length} 颗星<small>完成任务获得；领取阶段奖励不扣除</small></div></div><p class="help">每日任务按这台设备的日期，在零点重新开放。误触后可在任务卡片上取消今天的打卡，并扣回一颗星。</p><button class="primary-btn wide" id="exportData" ${storageError?'disabled':''}>导出星星备份</button><button class="soft-btn wide" id="importData">从备份恢复</button><input id="importFile" type="file" accept="application/json,.json" hidden><p class="help">在 iPad 中：用 Safari 打开网页 → 分享 → 添加到主屏幕。添加后请从主屏幕图标使用；若旧记录未出现，可导入备份。</p>`;return;}
 const type=tab,items=state[type],active=items.filter(t=>t.active),paused=items.filter(t=>!t.active);
 const row=x=>{const received=type==='rewards'&&state.claims.some(c=>c.rewardId===x.id);return `<div class="setting-row"><span class="emoji">${x.icon}</span><div class="setting-name">${esc(x.name)}<small>${type==='tasks'?'每日一次 · 每次 1 颗星':`累计 ${x.threshold} 颗星${received?' · 已领取':''}`}${!x.active?' · 已暂停':''}</small></div>${!received?`<button class="mini-btn" data-edit="${esc(x.id)}">编辑</button>`:''}<button class="mini-btn muted-btn" data-toggle="${esc(x.id)}">${x.active?'暂停':'恢复'}</button></div>`;};
 $('#settingsBody').innerHTML=`<p class="help">${type==='tasks'?'完成后点击一次，增加 1 颗星。暂停任务会保留历史星星，恢复后仍遵守每天一次。':'达到累计星星数后，每项奖励可以领取一次，不扣星星。已领取的奖励请添加新目标。'}</p>${active.map(row).join('')}${!active.length?'<p class="help">还没有设置，添加第一个吧。</p>':''}<button class="primary-btn wide" id="addItem">＋ 添加${type==='tasks'?'任务':'奖励'}</button>${paused.length?`<details style="margin-top:20px"><summary class="help">已暂停 ${paused.length} 项</summary>${paused.map(row).join('')}</details>`:''}`;
}
function openEditor(id=null){const item=state[tab].find(t=>t.id===id);editing={type:tab,id};selectedIcon=item?.icon||(tab==='tasks'?'📘':'🎁');$('#editorTitle').textContent=(id?'编辑':'添加')+(tab==='tasks'?'任务':'奖励');$('#itemName').value=item?.name||'';$('#itemName').placeholder=tab==='tasks'?'例如：英语阅读 15 分钟':'例如：一次家庭电影之夜';$('#itemThreshold').value=item?.threshold||10;$('#thresholdWrap').hidden=tab!=='rewards';$('#itemThreshold').required=tab==='rewards';$('#formError').textContent='';renderIcons();$('#editor').showModal();}
function renderIcons(){$('#iconPicker').innerHTML=ICONS.map(icon=>`<button type="button" data-icon="${icon}" class="${icon===selectedIcon?'selected':''}" aria-label="图标 ${icon}" aria-pressed="${icon===selectedIcon}">${icon}</button>`).join('');}
function confirmAction(title,message){return new Promise(resolve=>{$('#confirmTitle').textContent=title;$('#confirmText').textContent=message;const d=$('#confirmation');d.returnValue='';$('#confirmOk').onclick=()=>d.close('ok');$('#confirmCancel').onclick=()=>d.close('cancel');d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true});d.showModal();});}
$('#manage').onclick=()=>openSettings();$('#editRewards').onclick=()=>openSettings('rewards');$('#storageHelp').onclick=()=>openSettings('data');$('#closeSettings').onclick=()=>$('#settings').close();$('#closeEditor').onclick=()=>$('#editor').close();
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.complete)await checkin(b.dataset.complete);
 if(b.dataset.undo){const id=b.dataset.undo,day=dayKey(),record=state.completions.find(c=>c.taskId===id&&c.day===day);if(!record){refresh();return;}const name=state.tasks.find(t=>t.id===id)?.name||'这项任务';if(!await confirmAction('取消今天的打卡？',`将撤回「${name}」今天的记录，扣回 1 颗星。今天仍可重新完成。已领取的奖励会保留记录。`))return;const removed=await mutate(s=>{if(day!==dayKey())throw Error('已经是新的一天，未取消昨天的记录。');return cancelCompletion(s,id,day,record.at);});toast(removed?'已取消打卡，扣回 1 颗星':'这项打卡已经取消了');}
 if(b.id==='installApp'){updateInstallStatus();$('#installation').showModal();}
 if(b.id==='closeInstallation')$('#installation').close();
 if(b.dataset.open)openSettings(b.dataset.open);
 if(b.dataset.tab){tab=b.dataset.tab;renderSettings();}
 if(b.dataset.icon){selectedIcon=b.dataset.icon;renderIcons();}
 if(b.id==='addItem')openEditor();
 if(b.dataset.edit)openEditor(b.dataset.edit);
 if(b.dataset.toggle){const type=tab,x=state[type].find(x=>x.id===b.dataset.toggle);if(!x)return;const active=x.active;if(active&&!await confirmAction('暂停这项'+(type==='tasks'?'任务':'奖励')+'？','暂停后首页不再显示，已有星星和领取记录会保留，也可以随时恢复。'))return;await mutate(s=>{const item=s[type].find(x=>x.id===b.dataset.toggle);if(!item)throw Error('记录不存在。');item.active=!active;});toast(active?'已暂停，历史记录已保留':'已恢复');}
 if(b.dataset.claim){const r=state.rewards.find(r=>r.id===b.dataset.claim);if(!r)return;if(!await confirmAction('领取这份奖励？',`「${r.name}」已解锁，和家长一起确认领取吧。领取后星星仍会保留。`))return;await mutate(s=>claim(s,b.dataset.claim));celebrate();toast('奖励领取成功，继续积攒下一份期待！');}
 if(b.id==='exportData'){const raw=localStorage.getItem(KEY);if(!raw)throw Error('还没有可导出的记录。');validate(JSON.parse(raw));const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`星星打卡备份-${dayKey()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('备份已导出，请保存到“文件”中');}
 if(b.id==='importData')$('#importFile').click();
 }catch(e){toast(e.message||'操作未完成，请重试。');}});
$('#editForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await mutate(s=>saveItem(s,editing.type,editing.id,$('#itemName').value,selectedIcon,Number($('#itemThreshold').value)));$('#editor').close();toast('保存好了');}catch(e){$('#formError').textContent=e.message;}finally{btn.disabled=false;}};
document.addEventListener('change',async e=>{if(e.target.id!=='importFile')return;const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('文件过大，请选择星星打卡导出的备份。');const imported=validate(JSON.parse(await file.text()));if(!await confirmAction('从备份恢复？',`备份包含 ${imported.completions.length} 颗星星，将替换当前记录。建议先导出当前记录。`))return;const restore=()=>{write(imported);render();};if(navigator.locks?.request)await navigator.locks.request(KEY,restore);else restore();toast('星星和任务已恢复');}catch(e){toast(e instanceof SyntaxError?'文件格式不正确，请选择有效备份。':e.message);}finally{e.target.value='';}});
function refresh(){try{state=read();storageError=false;render();}catch{storageError=true;toast('记录读取失败，原始数据没有被覆盖。请在设置中恢复备份。');}}
try{state=read();if(localStorage.getItem(KEY)===null)write(state);}catch{storageError=true;state={version:1,tasks:[],rewards:[],completions:[],claims:[]};setTimeout(()=>toast('记录无法读取，未覆盖原始数据。请检查浏览器存储或恢复备份。'),200);}
render();window.addEventListener('storage',e=>{if(e.key===KEY)refresh();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});window.addEventListener('focus',refresh);setInterval(()=>{if(date!==dayKey())refresh();},15000);
let offlineReady=false,offlineFailure='';
function updateInstallStatus(){const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;$('#installTitle').textContent=installed?'已经安装到主屏幕':'安装到 iPad';$('#installSteps').hidden=installed;$('#installApp').textContent=installed?'应用状态':'安装到 iPad';$('#offlineStatus').textContent=offlineReady?(navigator.onLine?'✓ 离线资源已准备好，可断网使用':'✓ 正在离线使用，打卡照常保存'):offlineFailure||'正在准备离线使用，请保持联网片刻。';}
async function checkOffline(){if(!('serviceWorker'in navigator)){offlineFailure='当前浏览器不支持离线安装，请使用 iPad 的 Safari。';updateInstallStatus();return;}const worker=navigator.serviceWorker.controller;if(!worker)return;const channel=new MessageChannel();const timer=setTimeout(()=>channel.port1.close(),5000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();offlineReady=e.data?.version==='1.1.0'&&e.data?.ready===true;updateInstallStatus();};worker.postMessage({type:'OFFLINE_STATUS'},[channel.port2]);}
updateInstallStatus();
window.addEventListener('online',()=>{updateInstallStatus();checkOffline();});window.addEventListener('offline',updateInstallStatus);
if('serviceWorker'in navigator&&location.protocol!=='file:'){
 navigator.serviceWorker.addEventListener('controllerchange',checkOffline);
 navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(async registration=>{await navigator.serviceWorker.ready;checkOffline();registration.update().catch(()=>{});}).catch(()=>{offlineFailure='离线资源暂未准备好，请联网重新打开后再试。';updateInstallStatus();});
}

const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_star_progress',title:'查看星星打卡进度',description:'查看当前设备上的每日任务、累计星星和奖励。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{refresh();return{date:dayKey(),...state,storageError};}});register({name:'complete_daily_task',title:'完成每日任务',description:'将指定每日任务标记完成并增加一颗星；当天重复完成不会重复加星。',inputSchema:{type:'object',properties:{taskId:{type:'string'}},required:['taskId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input.taskId!=='string')throw Error('需要 taskId');return checkin(input.taskId);}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
